### ISSUE TITLE
torbrowser-launcher-0.1.8, new signing keys?

### ISSUE THREAD

**Issue by thunderrd** [MeisterP/torbrowser-overlay#10]
Thank you for maintaining the torbrowser overlay, it's appreciated.

There is a new deveopler signing key now, but tb-l-0.1.7 does not handle it.  I can verify manually, but it would be nice if we had the new launcher version in the overlay when you get the time to do it:

https://github.com/micahflee/torbrowser-launcher/tree/master/share

The new key is here:
https://hkps.pool.sks-keyservers.net/pks/lookup?op=vindex&search=0x4E2C6E8793298290

Thanks again for your work.

**Comment by MeisterP** [comment]
Thanks for reminding me

**Comment by thunderrd** [comment]
MeisterP, you might want to take a look at this, something I've just now seen:

https://github.com/micahflee/torbrowser-launcher/issues/157

Apparently there is a bug with running TB and non-tor FF concurrently; and a new[er] 0.1.9 version:

https://github.com/micahflee/torbrowser-launcher/blob/master/CHANGELOG.md

**Comment by thunderrd** [comment]
Oops, never mind, I see it's done and dusted.

Thank you, sir!
