### ISSUE TITLE
tor-browser-31.6.0esr-4.5-1-build3.tar.gz fetch failure

### ISSUE THREAD

**Issue by bircoph** [MeisterP/torbrowser-overlay#14]
>>> Downloading 'https://gitweb.torproject.org/tor-browser.git/snapshot/tor-browser-31.6.0esr-4.5-1-build3.tar.gz'
--2015-05-08 22:04:27--  https://gitweb.torproject.org/tor-browser.git/snapshot/tor-browser-31.6.0esr-4.5-1-build3.tar.gz
Resolving gitweb.torproject.org (gitweb.torproject.org)... 154.35.132.68
Connecting to gitweb.torproject.org (gitweb.torproject.org)|154.35.132.68|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/usr/portage/distfiles/tor-browser-31.6.0esr-4.5-1-build3.tar.gz’

/usr/portage/distfi     [               <=>    ] 162.34M  3.39MB/s   in 69s

2015-05-08 22:05:38 (2.34 MB/s) - ‘/usr/portage/distfiles/tor-browser-31.6.0esr-4.5-1-build3.tar.gz’ saved [170222459]

!!! Fetched file: tor-browser-31.6.0esr-4.5-1-build3.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      170222459
!!! Expected: 170222342
Refetching... File renamed to '/usr/portage/distfiles/tor-browser-31.6.0esr-4.5-1-build3.tar.gz._checksum_failure_.sucajs'

!!! Couldn't download 'tor-browser-31.6.0esr-4.5-1-build3.tar.gz'. Aborting.
 * Fetch failed for 'www-client/torbrowser-31.6.0_p450', Log file:
 *  '/var/tmp/portage/www-client/torbrowser-31.6.0_p450/temp/build.log'

**Comment by bircoph** [comment]
Probably upstream updated tarball without version change. Please update Manifest or issue new revbump.

**Comment by MeisterP** [comment]
Thanks. Apparently, the tag names changed.

```diff
diff tor-browser-31.6.0esr-4.5-1-build3 new/tor-browser-31.6.0esr-4.5-1-build3
diff --unified --new-file --recursive --show-c-function tor-browser-31.6.0esr-4.5-1-build3/addon-sdk/source/python-lib/cuddlefish/_version.py new/tor-browser-31.6.0esr-4.5-1-build3/addon-sdk/source/python-lib/cuddlefish/_version.py
--- tor-browser-31.6.0esr-4.5-1-build3/addon-sdk/source/python-lib/cuddlefish/_version.py	2015-04-24 16:40:44.000000000 +0200
+++ new/tor-browser-31.6.0esr-4.5-1-build3/addon-sdk/source/python-lib/cuddlefish/_version.py	2015-04-24 16:40:44.000000000 +0200
@@ -9,7 +9,7 @@
 # (https://github.com/warner/python-versioneer)
 
 # these strings will be replaced by git during git-archive
-git_refnames = " (tag: tor-browser-31.6.0esr-4.5-1-build3, tor-browser-31.6.0esr-4.5-1)"
+git_refnames = " (tag: tor-browser-31.6.0esr-4.5-1-build3)"
 git_full = "3006aa548cefa2f9d0968c978786dcefa9309119"
 

```
