### ISSUE TITLE
The `New Identity` feature doesn't work

### ISSUE THREAD

**Issue by mark-in** [MeisterP/torbrowser-overlay#17]
Could it be fixed?
For me it is strange that this feature doesn't work because of a tor's `ControlPort` is fairly available.
May be I should use the `torbrowser-launcher` to make it work?
BTW:  `torbrowser-launcher` doesn't work for me either. It is starts with download of  "update" and then just stops.

**Comment by MeisterP** [comment]
did you export the variables from https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/files/99torbrowser.example in your session? you can do so by copying the file to /etc/env.d, run env-update and then log out and back in into your graphical session.

**Comment by MeisterP** [comment]
To clarify:

If you use ```www-client/torbrowser```, you need to **adjust and export** the environment variables from [99torbrowser.example](https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/files/99torbrowser.example). You can do this either with gentoo's ```/etc/env.d``` mechanism  or on the commandline.

If you use ```www-client/torbrowser-launcher```, make sure that the environment variables from [99torbrowser.example](https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/files/99torbrowser.example) are **unset** and that you **don't** have the system wide tor running on port 9150.

**Comment by mark-in** [comment]
Great, thank you! Now it works like a charm.
P.S. Maybe it should be specified in the `README`?

**Comment by mark-in** [comment]
With defaulft settings a `TOR_CONTROL_PORT` variable is mandatory. Even if there is no password set. There is no default `ControlPort` or it is differs from `9051`?

**Comment by MeisterP** [comment]
No, there's no default value.
The default values would be set by the ```tor-launcher``` [extension](https://gitweb.torproject.org/tor-launcher.git/tree/src/defaults/preferences/prefs.js#n5) which is **not installed** by ```www-client/torbrowser```.
See this [line](https://gitweb.torproject.org/torbutton.git/tree/src/chrome/content/torbutton.js#n547) in the ```torbutton``` source code.

**Comment by MeisterP** [comment]
I'll work on an updated readme here:
https://gist.github.com/MeisterP/5d32e159ee1b67461f1c
You're welcome to add comments and/or clarifications.

**Comment by mark-in** [comment]
Poncho:
> No, there's no default value.
> The default values would be set by the ```tor-launcher``` [extension](https://gitweb.torproject.org/tor-launcher.git/tree/src/defaults/preferences/prefs.js#n5) which is **not installed** by ```www-client/torbrowser```.
> See this [line](https://gitweb.torproject.org/torbutton.git/tree/src/chrome/content/torbutton.js#n547) in the ```torbutton``` source code.


Thanks for pointing me out.
It's sounds quite reasonable for me not to set any default value. One
can start up several TorBrowser instances (TBB) with different
`ControlPort`s for each `tor` process.

Also I've noticed that `Tor Network Settings` button doesn't work. Maybe
it is have a similar cause? Or in order to make it work I should start
`tor-browser` via `tor-launcher`?

**Comment by mark-in** [comment]
Poncho:
> I'll work on an updated readme here:
> https://gist.github.com/MeisterP/5d32e159ee1b67461f1c
> You're welcome to add comments and/or clarifications.
Sure, thanks.

**Comment by MeisterP** [comment]
"Tor Network Settings" would configure the parameters to launch tor if it would be launched by ```tor-launcher``` extension in the user session. You don't need it with ```www-client/torbrowser``` since this package uses the system tor instance and therefore disables the ```tor-launcher``` extension.

**Comment by mark-in** [comment]
OK, got it.
Thanks!
