### ISSUE TITLE
failes to compile (gcc 5.2)

### ISSUE THREAD

**Issue by m4rkusxxl** [MeisterP/torbrowser-overlay#18]
Hi!

I just tried to compile torbrowser 5 with the current gcc 5.2.

I get this error:
In file included from …/torbrowser-38.2.0_p500/ff/security/manager/ssl/src/Unified_cpp_manager_ssl_src1.cpp:20:0:
…/torbrowser-38.2.0_p500/security/manager/ssl/src/nsNSSCallbacks.cpp: In static member function 'static void nsNSSHttpInterface::initTable()':
…/torbrowser-38.2.0_p500/security/manager/ssl/src/nsNSSCallbacks.cpp:601:16: error: invalid conversion from 'SECStatus (*)(SEC_HTTP_SERVER_SESSION, const char*, const char*, const char*, const char*, PRIntervalTime, void**) {aka _SECStatus (*)(void*, const char*, const char*, const char*, const char*, unsigned int, void**)}' to 'SEC_HttpRequest_CreateFcn {aka _SECStatus (*)(void*, const char*, const char*, const char*, unsigned int, void**)}' [-fpermissive]
   v1.createFcn = createFcn;

I have a normal firefox installed, too. gcc seems to use the typedef from the system include (/usr/include/nss/ocspt.h) for SEC_HttpRequest_CreateFcn.
(The system one has only three "const char*" parameters.)

I dont know if its an issue with this package or upstream.

**Comment by MeisterP** [comment]
can you try to remove the lines 
```
mozconfig_annotate 'torbrowser' --without-system-nspr
mozconfig_annotate 'torbrowser' --without-system-nss
```
at https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/torbrowser-38.2.0_p500.ebuild#L180

and rebuild torbrowser 5?

**Comment by MeisterP** [comment]
oh and did you use the master branch or the now deleted wip branch?

**Comment by m4rkusxxl** [comment]
nice catch... master is now working :)

**Comment by MeisterP** [comment]
The above error happens with gcc-4.8 as well. I've switched to the bundled nss and nspr libs to workaround the issue.

Probably one of the patches in https://gitweb.torproject.org/tor-browser.git/log/security/nss?h=tor-browser-38.2.0esr-5.0-1 introduced the incompatibility.
