### ISSUE TITLE
torbrowser-bin ebuild?

### ISSUE THREAD

**Issue by gbmaster** [MeisterP/torbrowser-overlay#23]
Do you think it would be possible to add a new ebuild that uses the already compiled version from the TOR project website? Just like the firefox-bin or the thunderbird-bin ebuilds already do

**Comment by MeisterP** [comment]
It might be possible, but I'm not interested in doing so. The upstream binaries are supposed to be installed in a user's home directory. There is `www-client/torbrowser-launcher` for downloading, verifying, running and proper desktop integration of the upstream binaries.
