### ISSUE TITLE
Cannot build torbrowser-45.3.0_p604 with GCC 6.2.0

### ISSUE THREAD

**Issue by fturco** [MeisterP/torbrowser-overlay#24]
After upgrading to gcc-6.2.0 I cannot build torbrowser-45.3.0_p604 anymore. I managed to build it by patching torbrowser with [this](https://bug1245076.bmoattachments.org/attachment.cgi?id=8715553) (from Firefox [bug 1245076](https://bugzilla.mozilla.org/show_bug.cgi?id=1245076))

[info.txt](https://github.com/MeisterP/torbrowser-overlay/files/451845/info.txt)
[torbrowser.txt](https://github.com/MeisterP/torbrowser-overlay/files/451862/torbrowser.txt)

**Comment by mpkh** [comment]
@fturco offtopic question: can you build whole world with that gcc version?

**Comment by fturco** [comment]
On my system I have 1209 packages. There are 15 packages other than `torbrowser` that I'm unable to build with `gcc-6.2.0`. For 8 of them I found patches online that fix build errors. For 7 of them I use workarounds such as adding `-std=gnu++98` to `CXXFLAGS`. But now I can emerge the whole world with the `-e` option without interruptions. I can share my findings if you want.

**Comment by mpkh** [comment]
@fturco maybe it will be need for me in some future but right now I had no plans to switch, just was interested in compatibility overall.

**Comment by fturco** [comment]
As you wish, but please remember that it is possible to keep two versions of GCC at the same time (for example 5.4.0 and 6.2.0). You can choose which version to use with `gcc-config`. There's even a small tool called `gcc-switcher` for telling Portage that certain packages should be compiled with a specific version of GCC using the `/etc/portage/package.compilers` configuration file. But unfortunately `gcc-switcher` didn't work on my system.

**Comment by MeisterP** [comment]
Does applying the [firefox-45-gcc6.patch](https://gitweb.gentoo.org/proj/mozilla.git/tree/www-client/firefox/files/firefox-45-gcc6.patch) from the mozilla overlay fix the the issue? Are you able to test this?

**Comment by fturco** [comment]
I successfully applied firefox-45-gcc6.patch instead of my own one. It works too.

**Comment by MeisterP** [comment]
See also https://bugs.gentoo.org/show_bug.cgi?id=582446
