### ISSUE TITLE
SRC_URI instead of git fetch

### ISSUE THREAD

**Issue by Ud71p** [MeisterP/torbrowser-overlay#28]
Hi, I tried to emerge your torbrowser ebuild, but my machine can only fetch via Tor. This means that git ebuilds don't work for me.

Would you please consider fetching the sources using SRC_URI?

This is possible, see example here:

https://github.com/4nykey/4nykey/blob/master/www-client/torbrowser/torbrowser-52.9.0.7.5.6.2.1.ebuild

For a bit of background why it's a better way, see:
https://github.com/deu/palemoon-overlay/issues/53

**Comment by MeisterP** [comment]
It's unfortunately not possible since the archives change with every tag that is added to the git repository.

See: https://github.com/MeisterP/torbrowser-overlay/issues/14 and https://github.com/MeisterP/torbrowser-overlay/issues/15
