### ISSUE TITLE
www-client/torbrowser: about src_uri

### ISSUE THREAD

**Issue by CaseOf** [MeisterP/torbrowser-overlay#32]
Hello,
I wouldn't bother you too much but I'm trying to understand why you did add binaries in SRC_URI in torbrowser ebuild. I didn't suceed yet to know why.
Would you explain me?
Sincerely,
Case_Of.

**Comment by MeisterP** [comment]
The binary package is necessary for the profile and for the docs.

See https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/torbrowser-60.5.1_p806.ebuild#L310 and https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/torbrowser-60.5.1_p806.ebuild#L318

```
equery f torbrowser | grep defaults/profile

/usr/lib64/torbrowser/defaults/profile
/usr/lib64/torbrowser/defaults/profile/bookmarks.html
/usr/lib64/torbrowser/defaults/profile/extensions
/usr/lib64/torbrowser/defaults/profile/extensions/https-everywhere-eff@eff.org.xpi
/usr/lib64/torbrowser/defaults/profile/extensions/tor-launcher@torproject.org.xpi
/usr/lib64/torbrowser/defaults/profile/extensions/torbutton@torproject.org.xpi
/usr/lib64/torbrowser/defaults/profile/extensions/{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi
```

**Comment by MeisterP** [comment]
Well, I hope this explanation was enough. Otherwise, feel free to reopen the issue.
