### ISSUE TITLE
www-client/torbrowser ignored environment variables.

### ISSUE THREAD

**Issue by crocket** [MeisterP/torbrowser-overlay#34]
/etc/env.d/99torbrowser inserted TOR_CONTROL_PORT and TOR_SOCKS_PORT into my environment, but those environment variables are ignored by torbrowser.

**Comment by MeisterP** [comment]
Does it work if you launch torbrowser from your terminal like:

> TOR_CONTROL_PORT=9151 TOR_SOCKS_PORT=9150 torbrowser


What's the output of 

> env | grep TOR_

**Comment by crocket** [comment]
```
> env | grep TOR_
TOR_CONTROL_HOST=127.0.0.1
TOR_CONTROL_PORT=9051
TOR_SOCKS_HOST=127.0.0.1
TOR_SOCKS_PORT=9050
```

torbrowser literally ignores TOR_SOCKS_HOST and TOR_SOCKS_PORT. torbrowser manages its own internal socks port number.

I cannot configure TOR_CONTROL_PORT in torbrowser.

**Comment by MeisterP** [comment]
> Does it work if you launch torbrowser from your terminal like:
> 
> > TOR_CONTROL_PORT=9151 TOR_SOCKS_PORT=9150 torbrowser

How about that? Maybe the variables are not exported to your desktop environment.

**Comment by MeisterP** [comment]
I can not reproduce your issue. All the variables in `/etc/env.d/99torbrowser` do work here.

**Comment by crocket** [comment]
> Maybe the variables are not exported to your desktop environment.

It's exported to my i3 session. I checked it in a terminal emulator in my i3 session.

**Comment by crocket** [comment]
I executed

```
env TOR_CONTROL_PORT=9051 TOR_SOCKS_PORT=9050 torbrowser
```

torbrowser's internal socks proxy configuration overrides environment variables. Environment variables are ignored.

**Comment by MeisterP** [comment]
> torbrowser's internal socks proxy configuration overrides environment variables. Environment variables are ignored.

I've changed nothing in torbrowser's internal configuration and the environment variables are honoured. So I guess you have to use either way to configure torbrowser to your liking.

> Perhaps, you didn't try to change tor ports. The default socks proxy port is 9150 in torbrowser.

I actually use `TOR_SOCKS_IPC_PATH=/var/run/tor/socks` and `TOR_CONTROL_IPC_PATH=/var/run/tor/control` in `/etc/env.d/99torbrowser` and it's working just fine.

**Comment by crocket** [comment]
I deleted

* ~/.mozilla/torbrowser
* ~/.cache

Suddenly, torbrowser starts allowing environment variables to override internal settings.
How weird.

**Comment by MeisterP** [comment]
> It seems that settings from torbrowser-launcher breaks torbrowser.

That might be, I don't know. I personally don't use `torbrowser-launcher`

**Comment by crocket** [comment]
This issue seems solved. Do you use cookie authentication for control port?
It seems to me that any authentication method that exposes the credential as an environment variable is not safe.

**Comment by MeisterP** [comment]
> Do you use cookie authentication for control port?

`TOR_SOCKS_IPC_PATH=/var/run/tor/socks` and `TOR_CONTROL_IPC_PATH=/var/run/tor/control` in conjuction with

```
SocksPort unix:/var/run/tor/socks GroupWritable
ControlPort unix:/var/run/tor/control GroupWritable
```
as my tor config.

**Comment by crocket** [comment]
What are the user and the group of tor instance for torbrowser?

**Comment by sijanec** [comment]
I have the same issue with the following uses:
```
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for www-client/torbrowser-115.7.0_p13009:
 U I
 + + X                  : Add support for X11
 + + clang              : Use Clang compiler instead of GCC
 + + dbus               : Enable dbus support for anything that needs it (gpsd, gnomemeeting, etc)
 - - hardened           : Activate default security enhancements for toolchain (gcc, glibc, binutils)
 + + pulseaudio         : Add sound server support via media-libs/libpulse (may be PulseAudio or PipeWire)
 + + system-av1         : Use the system-wide media-libs/dav1d and media-libs/libaom library instead of bundled
 + + system-harfbuzz    : Use the system-wide media-libs/harfbuzz and media-gfx/graphite2 instead of bundled
 + + system-icu         : Use the system-wide dev-libs/icu instead of bundled
 + + system-jpeg        : Use the system-wide media-libs/libjpeg-turbo instead of bundled
 + + system-libevent    : Use the system-wide dev-libs/libevent instead of bundled
 + + system-libvpx      : Use the system-wide media-libs/libvpx instead of bundled
 + + system-png         : Use the system-wide media-libs/libpng instead of bundled (requires APNG patches)
 - - system-python-libs : Use system's python site instead of bundled python libraries
 + + system-webp        : Use the system-wide media-libs/libwebp instead of bundled
 - - wayland            : Enable dev-libs/wayland backend
```

Tor Browser will not use environment variables for SOCKS5 proxy, no matter if I use TCP SOCKS5 or UNIX socket SOCKS5. I can see in /proc/pid/environ that the environment variables are indeed set for tor browser, but in about:config I can see that it still uses port 9150 for connections which are then refused.

Any ideas?

**Comment by bioluks** [comment]
Yes, even ignored when issuing environment variables via cmd prefixing.
