### ISSUE TITLE
=www-client/torbrowser-60.9.0_p855: Unable to link (hunspell errors)

### ISSUE THREAD

**Issue by redblade7** [MeisterP/torbrowser-overlay#35]
Hi,

I am unable to link =www-client/torbrowser-60.9.0_p855, it gives errors about Hunspell.

True of both ld.bfd and ld.gold.

Enabled USE flags for www-client/torbrowser are: clang,custom-cflags,custom-optimization,dbus,hardened,pulseaudio,startup-notification,system-harfbuzz,system-icu,system-jpeg,system-libevent,system-libvpx,system-sqlite

I do not have this problem with =www-client/firefox-69.0

Attached is the build log.

[build.log](https://github.com/MeisterP/torbrowser-overlay/files/3581381/build.log)

**Comment by redblade7** [comment]
No problems when removing the clang use flag from package.use.

**Comment by redblade7** [comment]
A note that =www-client/firefox-69.0 required clang/LLVM/etc be updated to v8.0.1. Before then I was using v7.1.0. So perhaps =www-client/torbrowser-60.9.0_p855 is not compatible with clang/LLVM/etc v8.0.1.

**Comment by MeisterP** [comment]
Are you able to build `www-client/firefox-60.9.0` with clang? (`60.9.0` not `69.0`, confusingly close version numbers these days...). This would be the firefox version that matches the source used by torbrowser

To be honest, I don't have the capacity to test different toolchains nor do I have the knowledge to fix linger bugs. If you can reproduce your issue with `www-client/firefox-60.9.0` from the gentoo tree, you could open a bug on gentoo's bugzilla and maybe get some help there.

**Comment by redblade7** [comment]
What version of the toolkit are you using?

**Comment by MeisterP** [comment]
`sys-devel/clang-7.1.0`, `sys-devel/llvm-7.1.0` and `sys-devel/lld-7.1.0` and building with `USE=clang` finishes successfully.

**Comment by redblade7** [comment]
=www-client/firefox-60.9.0 bug filed on Gentoo bug tracker:

https://bugs.gentoo.org/693698

**Comment by redblade7** [comment]
What are your other USE flags?

Mine for www-client/torbrowser are:

USE="clang custom-cflags custom-optimization dbus hardened pulseaudio startup-notification system-harfbuzz system-icu system-jpeg system-libevent system-libvpx system-sqlite"

and USE=clang for me won't work with v8.0.1.

Perhaps this is something relating to one of these system- packages using the gold linker?

**Comment by redblade7** [comment]
Removing all system- and custom- flags to use:

USE="clang dbus hardened pulseaudio startup-notification"

Still gives the hunspell errors.

I will try removing all except clang now.

**Comment by redblade7** [comment]
> 
> I will try removing all except clang now.

Nope, still doesn't work.

I usually use the gold linker and I'm wondering if some dependency I don't know about shouldn't be linked with gold for clang v8.0.1 to work.

**Comment by MeisterP** [comment]
> What are your other USE flags?

`USE="clang dbus pulseaudio startup-notification"`

I'm not using the gold linker, so I can't comment on that.

**Comment by redblade7** [comment]
I was able to compile the latest version (=www-client/torbrowser-68.2.0_p900) with USE=clang and ld.gold without any problems.

**Comment by MeisterP** [comment]
> I was able to compile the latest version (=www-client/torbrowser-68.2.0_p900) with USE=clang and ld.gold without any problems.

Same here. Building with clang as well as with gcc works fine on my end.

I don't think you're using the gold linker though, since `USE=clang` enforces `--enable-linker=lld`.
see https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/torbrowser-68.2.0_p900.ebuild#L324

**Comment by redblade7** [comment]
Should this bug remain open as =www-client/torbrowser-60.9.0_p855 is still available?
