### ISSUE TITLE
www-client/torbrowser-60.9.0_p855: cssparser: error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed

### ISSUE THREAD

**Issue by m4rkusxxl** [MeisterP/torbrowser-overlay#36]
torbrowser fails to compile:
 6:19.63    Compiling rayon v1.0.0
 6:22.74 error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
 6:22.74    --> /var/tmp/portage/www-client/torbrowser-60.9.0_p855/work/tor-browser-60.9.0esr-8.5-2-build2/third_party/rust/cssparser/src/parser.rs:572:17
 6:22.74     |
 6:22.74 547 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
 6:22.74     |                                                   - let's call the lifetime of this reference `'1`
 6:22.74 ...
 6:22.74 560 |             Some(ref cached_token)
 6:22.74     |                  ---------------- borrow of `self.input.cached_token` occurs here
 6:22.74 ...
 6:22.74 572 |                 self.input.cached_token = Some(CachedToken {
 6:22.74     |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
 6:22.74 ...
 6:22.75 584 |         Ok(token)
 6:22.75     |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`
 6:22.75 
 6:22.93    Compiling cstr v0.1.3
 6:23.08 error: aborting due to previous error
 6:23.08 
 6:23.08 For more information about this error, try `rustc --explain E0506`.
 6:23.10 error: Could not compile `cssparser`.
 6:23.10 warning: build failed, waiting for other jobs to finish...

**Comment by MeisterP** [comment]
Thanks for your report.
Please reopen if you still encounter the issue.
