### ISSUE TITLE
www-client/torbrowser-68.2.0_p901 fails to build.

### ISSUE THREAD

**Issue by crocket** [MeisterP/torbrowser-overlay#38]
[build.500.log](https://github.com/MeisterP/torbrowser-overlay/files/3889739/build.500.log)
[emerge.info.log](https://github.com/MeisterP/torbrowser-overlay/files/3889740/emerge.info.log)
[environment.log](https://github.com/MeisterP/torbrowser-overlay/files/3889741/environment.log)

```
> equery u torbrowser | cat
-clang
-cpu_flags_x86_avx2
-custom-cflags
-custom-optimization
-dbus
-hardened
-pulseaudio
+startup-notification
+system-av1
+system-harfbuzz
+system-icu
+system-jpeg
+system-libevent
+system-libvpx
+system-sqlite
+system-webp
```

**Comment by MeisterP** [comment]
I've pulled in some fixes for llvm and rust related issues in https://github.com/MeisterP/torbrowser-overlay/commit/8c0471c99d84baa9580f3c5de7943b81e98b377c
Please re-sync and try again.

If you still have issues, try emerging `=www-client/firefox-68.2.0` with the same useflags as you use for `www-client/torbrowser-68.2.0_p901` and report back.

**Comment by crocket** [comment]
I re-synced. It was built.
