### ISSUE TITLE
torbrowser fails to build with rust-1.43

### ISSUE THREAD

**Issue by papjul** [MeisterP/torbrowser-overlay#40]
`
 4:18.33 error: casts cannot be followed by a field access
 4:18.34     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
 4:18.34 error: casts cannot be followed by a field access
 4:18.34     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
 4:18.35 error: casts cannot be followed by a field access
 4:18.35     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
 4:18.35 error: casts cannot be followed by a field access
 4:18.35     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
 [...]
 4:39.37 error: aborting due to 4 previous errors
 4:39.41 error: could not compile `style`.
`

It seems it requires a patch:
https://gitweb.gentoo.org/repo/gentoo.git/commit/www-client/firefox/firefox-68.7.0-r1.ebuild?id=052da9d6733c8981f199211d94d3cab6b4a783cd

**Comment by MeisterP** [comment]
I fixed this locally but forgot to push it.... should be working now. Please reopen otherwise.

**Comment by papjul** [comment]
I had to fix this locally because for some reason overlay was not updating, even after removing timestamp.chk

**Comment by MeisterP** [comment]
> I had to fix this locally because for some reason overlay was not updating, even after removing timestamp.chk

Well, the commit is there https://github.com/MeisterP/torbrowser-overlay/commit/367b3acf42bac3ad828dd332bf45c79390060ab2
it should sync properly at some point.
