### ISSUE TITLE
nodejs dependency?

### ISSUE THREAD

**Issue by ordex** [MeisterP/torbrowser-overlay#43]
While installing totbrowser through this ebuild I noted that portage wanted t pull nodejs as well.
Any reason for that?

Nodejs does not seem to be listed as torbrowser dependency anywhere (also AUR does not pull it in: https://aur.archlinux.org/packages/tor-browser/)

**Comment by MeisterP** [comment]
> While installing torbrowser through this ebuild I noted that portage wanted to pull nodejs as well.
> Any reason for that?

The [firefox ebuild in ::gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/firefox-68.12.0.ebuild#n144) depends on >=net-libs/nodejs-8.11.0 and the torbrowser ebuild basically mirrors the firefox ebuild (ease of maintenance).

> Nodejs does not seem to be listed as torbrowser dependency anywhere (also AUR does not pull it in: https://aur.archlinux.org/packages/tor-browser/)

This package installs the binary provided by the tor project and doesn't build the browser from source. Therefore doesn't need any build time dependencies.

**Comment by ordex** [comment]
Ouch! I didn't realize this ebuild was aiming at compiling torbrowser from scratch. I was hoping it would go for the bundled/binary version.
I guess this issue can be closed then.

Thanks for your reply.

**Comment by MeisterP** [comment]
> Ouch! I didn't realize this ebuild was aiming at compiling torbrowser from scratch

Welcome to Gentoo 😂
