### ISSUE TITLE
torbrowser-launcher faulty version checking

### ISSUE THREAD

**Issue by corvus1** [MeisterP/torbrowser-overlay#46]
Due to some peculiarities of version checking, it thinks that version 10 is older than version say 9. Here's the fix:
https://github.com/micahflee/torbrowser-launcher/pull/499

**Comment by MeisterP** [comment]
Tanks for reporting. Merged the fix and updated the developer keys as well.

**Comment by corvus1** [comment]
Cool, thanks.

**Comment by corvus1** [comment]
The upstream really needs to release a new version, or we will be doomed to keep picking up patches. :-)
