### ISSUE TITLE
www-client/torbrowser-launcher won't start: key expired

### ISSUE THREAD

**Issue by redblade7** [MeisterP/torbrowser-overlay#47]
I attempted to start www-client/torbrowser-launcher, it tries to download an update and fails due to the key being expired.

I don't use the computer in question very often so I'm not sure when this problem started.

**Comment by MeisterP** [comment]
Can you try re-emerging `www-client/torbrowser-launcher`? I've added a patch that updates the keys about two weeks ago in https://github.com/MeisterP/torbrowser-overlay/commit/724f1a2f1006823fa68265a2dd4041d075ba5fdd
Maybe that fixes your issue...

**Comment by redblade7** [comment]
Yep, re-emerging fixed it. Thank you!
