### ISSUE TITLE
www-client/torbrowser-78.5.0_p1005 fails to build.

### ISSUE THREAD

**Issue by keke-cute** [MeisterP/torbrowser-overlay#50]
[build.log](https://github.com/MeisterP/torbrowser-overlay/files/5608000/build.log)
* www-client/torbrowser [2]
     Available versions:  (~)78.5.0_p1005 {clang dbus hardened pulseaudio +system-av1 +system-harfbuzz +system-icu +system-jpeg +system-libevent +system-libvpx +system-webp}

**Comment by keke-cute** [comment]
installed firefox version:www-client/firefox-83.0

**Comment by MeisterP** [comment]
This is probably the same issue as https://bugs.gentoo.org/756334
I've pushed a possible fix in 12c2342749cd9cbe8b90ee602315208dd3f501c4
Please re-sync and try again.

**Comment by keke-cute** [comment]
> This is probably the same issue as https://bugs.gentoo.org/756334
> I've pushed a possible fix in [12c2342](https://github.com/MeisterP/torbrowser-overlay/commit/12c2342749cd9cbe8b90ee602315208dd3f501c4)
> Please re-sync and try again.

Thank you, build done ! but :

Something Went Wrong!

Tor is not working in this browser.

**Comment by keke-cute** [comment]
![image](https://user-images.githubusercontent.com/37539103/100493916-18b02b80-3177-11eb-863e-e150ae1dc2b4.png)

**Comment by keke-cute** [comment]
Sorry, this my port error,solved
