### ISSUE TITLE
onionshare 0.6 ebuild

### ISSUE THREAD

**Issue by Kalle72** [MeisterP/torbrowser-overlay#51]
The ebuild does not work, because at http://ftp.debian.org/debian/pool/main/o/onioncircuits/ is no corresponding file. Only the versions 0.7 and 0.5 are available.

**Comment by MeisterP** [comment]
Thanks for the report

**Comment by Kalle72** [comment]
Thanks for the ebuild ;-)

Poncho:
> Thanks for the report
>
