### ISSUE TITLE
Configure on arm64 errors: --disable-eme is not available in this configuration

### ISSUE THREAD

**Issue by midnightpizza** [MeisterP/torbrowser-overlay#59]
It appears the ebuild hardcodes, --disable-eme. This Causes the build to fail on aarch64 with:  mozbuild.configure.options.InvalidOptionError: --disable-eme is not available in this configuration

I have tried removing it from  the ebuild, but something else that i cannot find is also pulling it in as default.

Build Log:
[build.log](https://github.com/MeisterP/torbrowser-overlay/files/8236885/build.log)

**Comment by MeisterP** [comment]
The ebuild has no keywords for arm64. How is it even possible to install it on a aarch64 system?

```
               a a   a           p r   s
               l m   r h i m m   p i s p   e s r
               p d a m p a 6 i p c s 3 a x a l e
               h 6 r 6 p 6 8 p p 6 c 9 r 8 p o p
               a 4 m 4 a 4 k s c 4 v 0 c 6 i t o
---------------------------------------------------------
 91.7.0_p11007 o ~ o o o o o o o o o o o ~ 7 0 torbrowser
```

**Comment by midnightpizza** [comment]
Well i unmasked it, using package.accept_keywords,  www-client/torbrowser **
Since there are no actual upstream builds for anything but x86 CPU's. 
This would be the only way to have a working torbrowser on aarch64, without having to trust a third party binary. (and possibly other architectures)

**Comment by MeisterP** [comment]
> Well i unmasked it, using package.accept_keywords, www-client/torbrowser **

Please don't fill bugs when using unsupported architectures. 


In case you want to do some hacking on your own fork:
- config for official builds are here: https://gitweb.torproject.org/builders/tor-browser-build.git/tree/projects/firefox?h=maint-11.0
- you probably need to inject this here: https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/torbrowser-91.7.0_p11007.ebuild#L475
