### ISSUE TITLE
Torbrowser-launcher and qt

### ISSUE THREAD

**Issue by Kalle72** [MeisterP/torbrowser-overlay#63]
Hello,

if I run the torbrowser-launcher from the applications menu nothing happens.

If I run torbrowser-launcher from the terminal I get the following error:

"Cannot mix incompatible Qt library (5.15.4) with this library (5.15.5)" (On my machine 5.15.5 is installed.)

Is there any way to overcome this. If I see it right, qt 5.15.4 is not available anymore via gentoo's official repository.

Thanks in advance and kind regards
Kalle72

**Comment by MeisterP** [comment]
Does re-emerging torbrowser-launcher fix the issue?
`emerge -1 torbrowser-launcher`

**Comment by Kalle72** [comment]
Unfortunately a new merge changes nothing, but my installation was also a "fresh one". 

Until now I used the torbrowser alongside with a system-tor. Now I want to switch to the launcher. This because I use sometimes an outdated torbrowser, because of the long compile times. But with the compiled version everything worked well.

**Comment by MeisterP** [comment]
Did you figure out which qt library was causing your issues?
