### ISSUE TITLE
/usr/bin/torbrowser not POSIX compliant

### ISSUE THREAD

**Issue by MrRoy** [MeisterP/torbrowser-overlay#65]
Hello,
The torbrowser script uses `/bin/sh` (https://github.com/MeisterP/torbrowser-overlay/blob/master/www-client/torbrowser/torbrowser-102.6.0_p12001.ebuild#L739) but it not POSIX compliant. If you use a POSIX shell, the if condition gives an error.

Using `dash`:
```
$ /usr/bin/torbrowser 
/usr/bin/torbrowser: 9: [[: not found
```
This is because of the double square brackets `[`; to fix it you can just put a single `[` , such as : 
```
if true && [ -z ${MOZ_DISABLE_WAYLAND} ]; then
if [ -n "${WAYLAND_DISPLAY}" ]; then
export MOZ_ENABLE_WAYLAND=1
fi
fi
```
Another option is to use `#!/bin/bash`

**Comment by MeisterP** [comment]
> Another option is to use `#!/bin/bash`

Going with that option since it's the same as `www-client/firefox::gentoo` is using in https://github.com/gentoo/gentoo/blob/master/www-client/firefox/files/firefox-r1.sh#L1

Thanks for the report.
