### ISSUE TITLE
Fonts are messed up

### ISSUE THREAD

**Issue by l29ah** [MeisterP/torbrowser-overlay#66]
It used to work fine a couple of months ago, but now it can't utilize fonts in the UI and most of web pages:
![](https://tinystash.undef.im/il/NxgZo28VaosZUpfeQDNZobpdXem6CTGK2LDSMcQKtob9e4K7HteCQMg1AkZgJ6wsbsxdj8ghXSG7Dp14QRetsK2.png)
Maybe it depends on a particular font being present that is absent on my system and is not reflected in RDEPEND?

**Comment by MeisterP** [comment]
I can not reproduce this locally.

Does installing `media-fonts/noto` fix your issue?

**Comment by l29ah** [comment]
Yes, installing this 1GB font fixed the problem.

**Comment by l29ah** [comment]
Although, rendering of a cyrillic document in google docs still fails: https://tinystash.undef.im/il/3i3YFbq8nNNbBnwUmVahVXVTfSgFCZuiYgkVDKa99L8kA1DKXKD5vH1p25FQ35A2KDAaHx34VhnABHUL6dNM5yvW.png

**Comment by MeisterP** [comment]
Does it work with `www-client/firefox-102.13.0` from the gentoo repository?

> Yes, installing this 1GB font fixed the problem.

maybe another font works too. noto is the one I'm using.

**Comment by l29ah** [comment]
Everything works with www-client/firefox-115.0.2, and seems like it's impossible to install www-client/firefox-102.13.0 without resorting to binary packages given i have dev-lang/rust-1.70.0 installed :(

**Comment by MeisterP** [comment]
> Everything works with www-client/firefox-115.0.2, and seems like it's impossible to install www-client/firefox-102.13.0 without resorting to binary packages given i have dev-lang/rust-1.70.0 installed :(

That's alright, thanks for testing. Doesn't seem to be a system wide fontconfig issue then.

Another thing you could try is to replace `--enable-bundled-fonts \` with `--disable-bundled-fonts \` in
https://github.com/MeisterP/torbrowser-overlay/blob/779a9dcf619159db61dffa94eadd80584684c96a/www-client/torbrowser/torbrowser-102.13.0_p12501.ebuild#L539C1-L539C27
and then recompile torbrowser. Since I can't reproduce the issue, I can't test this myself. It's just a guess.

**Comment by amano-kenji** [comment]
I also have this issue.

**Comment by MeisterP** [comment]
Does it work if you change `layout.css.font-visibility.resistFingerprinting` to `3` in `about:config`?

See https://support.mozilla.org/en-US/questions/1389771 for an explanation about fonts and fingerprinting

**Comment by amano-kenji** [comment]
No.

**Comment by MeisterP** [comment]
These are the fonts that torbrowser uses: https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/blob/main/projects/fonts/config

The corresponding packages on gentoo are:
`media-fonts/croscorefonts`
`media-fonts/noto`

Can you try whether installing these two fixes your issues?

**Comment by amano-kenji** [comment]
I already have `media-fonts/noto`. I installed `media-fonts/croscorefonts`, and the issue wasn't fixed.

**Comment by amano-kenji** [comment]
> Do you have USE=clang by any chance?

Yes for `web-client/torbrowser`.

**Comment by l29ah** [comment]
> > Do you have USE=clang by any chance?
> 
> Yes for `web-client/torbrowser`.

Try rebuilding with -clang. I made lots of changes at once, but likely this one fixed the problem for me.

**Comment by amano-kenji** [comment]
Actually, `clang` USE flag is enabled by default in torbrowser.

**Comment by amano-kenji** [comment]
Building torbrowser without `clang` USE flag doesn't fix the issue.

**Comment by MeisterP** [comment]
So @l29ah's issue was fixed by installing the two mentioned font packages?

> Yes, installing this 1GB font fixed the problem.

`media-fonts/noto` fixed part of the issue....

> Although, rendering of a cyrillic document in google docs still fails

This should be fixed by `media-fonts/croscorefonts`

If this steps don't work for @amano-kenji, then it's a different issue.

**Comment by l29ah** [comment]
Then it's `--disable-bundled-fonts` that did the job.

**Comment by amano-kenji** [comment]
I installed the latest version of www-client/torbrowser, but I still have the broken fonts on torbrowser.
